### ISSUE TITLE
誤字報告と要望

### ISSUE THREAD

**Issue by Xenon-kk** [penguin117117/MSBT_Editor#13]
【誤字報告】
アイコンタグの隠しスターの文字が「隠しシスター」となっています。
他の作業が完了したときにでも修正していただけると助かります。
【要望】
msbt・msbfファイルを保存した際に、ウィンドウのどこかに保存完了の文字を表示していただけると
しっかり保存されたかどうかの確認ができてありがたいです。
ウィンドウ下部の「保存したファイル：」がそれにあたるのでしたら、
保存しても：の右にファイル名が表示されないので修正をお願いします。

**Comment by penguin117117** [comment]
# この問題について
これらの問題に関しては技術的にすぐ対応できます。
## 誤字報告に関して
誤字の件に関しては、英語翻訳される際に、日本語のアイコンが消えていたため、
私が、いくつか前のバージョンの構文を流用したことによるものだと思われます。
もしかしたら、いくつか足りないアイコンがある可能性があるので、こちらで調査してみます。
## 要望に関して
保存したファイルを表示する機能は実装しようとしていましたが、すっかり忘れていました。
これに関しても対応します。
## 対応状況
- [ ] 誤字の件
- [ ] 要望の件

**Comment by penguin117117** [comment]
この問題は解決しました #13

**Comment by penguin117117** [comment]
この問題は解決しました #13
