### ISSUE TITLE
ATR1セクションの不具合報告と要望

### ISSUE THREAD

**Issue by Xenon-kk** [penguin117117/MSBT_Editor#15]
【不具合】
既存のリストのATR1セクションを編集する際、NPCボイスの値の変更が反映されません。修正をお願いします。

【要望】
「MSBT開く」と「MSBF開く」の機能およびボタンを統合していただきたいです。具体的には、
　- ウィンドウ左上のファイルタブの「MSBT開く」と「MSBF開く」を「ファイルを開く」のひとつにまとめる
　- 開くファイル選択時のフィルターをmsbt, msbf別々ではなくひとつにまとめる
　- 開くファイルの複数選択を可能にする
この3点をお願いします。

**Comment by penguin117117** [comment]
不具合に関しては、早急に修正いたします。

要望に関してですが、技術的には可能と思われますが、以下の点で導入をするべきではないと思っています
①初心者が使用した際にわかりづらい
②複数選択できるソフトが珍しいのでその機能に気づいてもらえない。
③要望されている機能に関しては現状ドラッグアンドドロップで対応済み。
②ARCファイルを開く機能を実装予定である。

**Comment by penguin117117** [comment]
不具合と要望に対応しましたので
このIssuesを閉じます。
