### ISSUE TITLE
arcファイルが適切に開けない

### ISSUE THREAD

**Issue by Xenon-kk** [penguin117117/MSBT_Editor#19]
## 不具合内容
msbtファイルのみを格納しているarcファイルを開くと、
以降すべてのARCファイルの中身リストをクリックしても選択できなくなり
MSBT、FLW2、FEN1リストも更新されなくなる。
ウィンドウを閉じることでこの不具合は解消される。
msbtファイルのみを格納しているarcファイルなら、どのファイルでもこの不具合が起こりうる模様。
不具合の発生タイミングもランダム(？)で、msbtファイルのみを格納しているarcファイルを1回開いても
必ずこの不具合が発生するとは限らない。

## 再現手順
1. 任意の方法で、msbtファイルのみを格納しているarcファイルを開く。
2. 不具合が発生するまで1. の作業を繰り返す。

**Comment by penguin117117** [comment]
不具合は解決しましたので、このIssuesを閉じます。
