### ISSUE TITLE
未知のタグ発見報告

### ISSUE THREAD

**Issue by Xenon-kk** [penguin117117/MSBT_Editor#3]
SystemMessage内のWiiMessage.msbtにて<Unknown="Tag07">を発見したので報告させていただきます。

**Comment by penguin117117** [comment]
報告ありがとうございます。
早急に対応します。

**Comment by penguin117117** [comment]
> SystemMessage内のWiiMessage.msbtにて<Unknown="Tag07">を発見したので報告させていただきます。

この問題を解決しました！
次回リリース時に適用されます

**Comment by Xenon-kk** [comment]
ありがとうございます！

**Comment by penguin117117** [comment]
解決したのでこのissueを閉じます。
